# Generated by Django 4.0.4 on 2022-04-22 02:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0002_alter_resume_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cv',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
