# Generated by Django 4.0.4 on 2022-04-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0003_alter_resume_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='resume',
        ),
        migrations.AddField(
            model_name='comment',
            name='resume',
            field=models.ManyToManyField(to='seekers.resume'),
        ),
    ]
